services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: fyp2025
      MYSQL_USER: fyp
      MYSQL_PASSWORD: fyp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pfyp", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: flask-app
    restart: always 
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
    env_file:
      - .env
    volumes:
      - ./log:/log 
      - ./uploads:/uploads 
      - ./resource_app:/resource_app
  
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_net
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  mysql_data:

networks:
  app_net:

